### ISSUE TITLE
SyntaxError: Unexpected token T

### ISSUE THREAD

**Issue by woodland-appcolony** [assertible/lambda-cloudwatch-slack#24]
Looks like a great lambda implementation, would love to use it, but it seems to be doing something odd.

First, Lambda's default SNS test event causes this failure:

```
2017-11-28T19:37:15.286Z	1a21cdd9-d473-11e7-89a1-a3392781a961	SyntaxError: Unexpected token T
at Object.parse (native)
at handleCatchAll (/var/task/index.js:282:24)
at processEvent (/var/task/index.js:347:20)
at exports.handler (/var/task/index.js:370:5)
```

Second, I sent Elastic Beanstalk events through SNS to this Lambda code, and strangely enough it was being handled by the catch-all, not the Elastic Beanstalk handler.

And, those Beanstalk events would fail with the exact same error above.

**Comment by JeroenRijks** [comment]
Hey @woodland-appcolony , I know this was two and a half years ago, but I'm running into the same issue, only with EC2 events through SNS, instead of Elastic Beanstalk. Did you figure out what the issue is?
