### ISSUE TITLE
The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions.

### ISSUE THREAD

**Issue by 0xM** [assertible/lambda-cloudwatch-slack#52]
It does not work anymore.

`InvalidParameterValueException: The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions.
    at Object.extractError (/tmp/lambda-cloudwatch-slack/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.extractError (/tmp/lambda-cloudwatch-slack/node_modules/aws-sdk/lib/protocol/rest_json.js:52:8)
    at Request.callListeners (/tmp/lambda-cloudwatch-slack/node_modules/aws-sdk/lib/sequential_executor.js:109:20)
    at Request.emit (/tmp/lambda-cloudwatch-slack/node_modules/aws-sdk/lib/sequential_executor.js:81:10)
    at Request.emit (/tmp/lambda-cloudwatch-slack/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/tmp/lambda-cloudwatch-slack/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/tmp/lambda-cloudwatch-slack/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /tmp/lambda-cloudwatch-slack/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/tmp/lambda-cloudwatch-slack/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/tmp/lambda-cloudwatch-slack/node_modules/aws-sdk/lib/request.js:685:12) {
  message: 'The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions.',                                                                                                                                             
  code: 'InvalidParameterValueException',
  time: 2020-02-22T05:12:22.793Z,
  statusCode: 400,
  retryable: false,
  retryDelay: 99.56550639994093
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lambda-cloudwatch-slack@0.3.0 deploy: `./scripts/deploy.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lambda-cloudwatch-slack@0.3.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by exilemirror** [comment]
run npm install node-lambda@latest before deploying.
Just tested mine today and it works!

**Comment by ferdinandfrank** [comment]
@exilemirror I can confirm that this worked! Thank you! :)
