### ISSUE TITLE
 Error: certificate has expired at TLSSocket

### ISSUE THREAD

**Issue by anil-venkata** [assertible/lambda-cloudwatch-slack#76]
Hi ,

It was stopped working from last two weeks. and I am getting this error in cloudwatch logs.

```
Error: Runtime exited with error: exit status 1 Runtime.ExitError
Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)
```
Not sure which certification it is looking for. Can you please help with this.

Please do let me know if you required any more details for debugging purpose. Thanks in advance.

**Comment by sameeraksc** [comment]
Same for us @CodyReichert

**Comment by creichert** [comment]
Hey guys, sorry about this I haven't been receiving notifications for this repo in my inbox.

Are you still seeing this issue? I can look at it tomorrow. Please ping me directly for now if you have any updates so I'm sure to get the notification.
